language: java
sudo: required
services:
  - docker
before_install:
  - docker pull stain/jena-fuseki
  - docker run  -d -p 3030:3030 -e ADMIN_PASSWORD=cinderella stain/jena-fuseki
  - sudo apt-get update -qq
  - sudo apt-get install -y serdi raptor2-utils
script:
    - bash scripts/eCH0071/build.sh
deploy:
  edge: true
  provider: releases
  api-key:
    - secure: "oBxeqP8nVTJ60N6VapGvvruAx4jhs2fvEV9wem1Ax7y8IxI3NniEjIJLXbTEfQ/ZNWqTeKXGlZ+UWaltNw2/Zdl2j3W9VSjqJGzaZAWX68T0gsA1YuecFfv65HTFgu/KiBEprmv0maxJSD9EKUR4JOzZapaoiuW/E5RuveLGCOCFTDuh5E99KzkHv1cmoz1Ap/ApNx4tBitp/AoFjww5sMREMxHz4XDdlTrw6rhcrBp6/MVLwD3Hls2DiCHRXtKP9oQiF5fEzgtBR4umqHLaexzjysQ9XE6VPOuhSZO6mKwM4I/Trk9TDCsJYOf1mr75yaZGH31peu2hXBODqPq9icYqPvP8ngnfXkZXF9eH/NiV/kPGrSNg0kxvXNyltBLzhQdmpEbJgmDrkuqq1MO9p5eNXyc5+TLGK11ynQ4x6jYJukY9uSRlFAuaSG8UFNtlGU/0rnW66LOezS9L5wRFQaqM21DhQvTlz9prrNJ3WT39QOmWeq3uRMlP3UvYP3s4p1IjOs7wO0r/Tc00mCRfk7RXWzK4PGwRNrkf0aKOnocd7lazZscVpXnP+rgVIpsbKu/x9UjM2zOGU8/67Zu6J3XNAXO3RgeNQREpS+eqXCsyTfZtbMuRSUyrMxA79j7U6qkv0OoibPP0LtFx7EDQLh9XJGqTAtZbDwwnjPv49H4="
  file: target/eCH0071-final.nt
  on:
    tags: true
    all_branches: true
